apiVersion: v1
kind: Service
metadata:
  name: jerney-db
  namespace: {{ .Values.namespace }}

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: jerney-db

  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
