apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jerney-db-pvc
  namespace: jerney
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
