apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jerney-ingress
  namespace: jerney
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "jerney-ingress-ip"
    networking.gke.io/managed-certificates: "jerney-certificate"

spec:
  rules:
    - host: jerney.rohith-gowda.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jerney-frontend
                port:
                  number: 80